### ISSUE TITLE
When emptying the bin, the empty state is displayed very quickly and then, it disappeared

### ISSUE THREAD

**Issue by tevincent** [Infomaniak/android-kDrive#1171] opened 2024-01-11 13:44 UTC

**Comment by tevincent** [comment] 2024-01-11 16:29
@sirambd is that fixed with branch api_v3 branch ? I've tested on your branch and the issue is no longer there.

**Comment by sirambd** [comment] 2024-01-12 15:21
With api V3 a lot of bugs have been fixed, by changing the logic, so it is possible that this will be fixed.
So if you can't reproduce the bug, that simply means that it's fixed, so let's assume that it's fixed until proven otherwise.

**Closed by sirambd** 2024-01-12 15:21 UTC
Labels: bug
