### ISSUE TITLE
You cannot change an invited user permission neither delete it

### ISSUE THREAD

**Issue by didi1245** [Infomaniak/android-kDrive#22] opened 2021-05-20 08:33 UTC
When I share a directory the other not seem to be share so we can't remove the acces to the other directory. And the acces is a writing we can't choose if the people just can read or writing to the files.

**Comment by Kilian-Perisset** [comment] 2021-05-20 10:44
Hello, 

I'm able to reproduce your problem. 

To reproduce :
- Go to `Sharing & rights` of a file/folder
- Share access of a file to someone with his email address
- Chose a permission for the invited user

Then you cannot : 
1. Change back his permission
2. Delete invited user from invitations

**Comment by didi1245** [comment] 2021-05-20 11:21
For exemple  this screen
![Screenshot_20210520-131957_kDrive](https://user-images.githubusercontent.com/83926216/118970118-28623d00-b96e-11eb-8c0d-fd9cc3f40c2b.jpg)
I share this directory is contain this under directory and a for a is not seem share

**Comment by didi1245** [comment] 2021-05-20 11:24
![Screenshot_20210520-132321_kDrive](https://user-images.githubusercontent.com/83926216/118970483-927ae200-b96e-11eb-9504-9da771dcd675.jpg)
 For exemple this https://drive.infomaniak.com/app/share/263955/394d20cd-7164-4e43-b5a3-99bd82ac21d1

**Comment by didi1245** [comment] 2021-05-20 11:25
It's problem

**Comment by Kilian-Perisset** [comment] 2021-05-20 11:36
Permissions/shares recurrence seems to be another problem than the initial. 
I'll create another issue and explain this to facilitate our "bug management" ;) : https://github.com/Infomaniak/android-kDrive/issues/24

**Comment by Kilian-Perisset** [comment] 2021-05-20 15:03
Fixed by : https://github.com/Infomaniak/android-kDrive/pull/26
and https://github.com/Infomaniak/android-kDrive/commit/a272d0623a71f428f79b80aee80303e8eaf778c2

It fixes : 
- Denied user deletion when an user was external (I think it was your case because you're on a "Solo" offer)
- Denied user permission change to manage (when user is external) it was missing UI warning

Thank you very much for your returns 🙏 
I close this issue, do not hesitate to create a new one if you encounters an issue.

**Closed as completed by Kilian-Perisset** 2021-05-20 15:03 UTC
Labels: bug
